/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as DashRouteImport } from './routes/dash'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardRemindersIndexRouteImport } from './routes/dashboard/reminders/index'
import { Route as DashboardMeetingsIndexRouteImport } from './routes/dashboard/meetings/index'
import { Route as DashboardFavoritesIndexRouteImport } from './routes/dashboard/favorites/index'
import { Route as DashboardContactsIndexRouteImport } from './routes/dashboard/contacts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardSettingsAppearanceIndexRouteImport } from './routes/dashboard/settings/appearance/index'
import { Route as DashboardSettingsAccountIndexRouteImport } from './routes/dashboard/settings/account/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardRemindersIndexRoute = DashboardRemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMeetingsIndexRoute = DashboardMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFavoritesIndexRoute = DashboardFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsAppearanceIndexRoute =
  DashboardSettingsAppearanceIndexRouteImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsAccountIndexRoute =
  DashboardSettingsAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dash': typeof DashRoute
  '/todos': typeof TodosRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/favorites/': typeof DashboardFavoritesIndexRoute
  '/dashboard/meetings/': typeof DashboardMeetingsIndexRoute
  '/dashboard/reminders/': typeof DashboardRemindersIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/settings/account/': typeof DashboardSettingsAccountIndexRoute
  '/dashboard/settings/appearance/': typeof DashboardSettingsAppearanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash': typeof DashRoute
  '/todos': typeof TodosRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/favorites': typeof DashboardFavoritesIndexRoute
  '/dashboard/meetings': typeof DashboardMeetingsIndexRoute
  '/dashboard/reminders': typeof DashboardRemindersIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountIndexRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dash': typeof DashRoute
  '/todos': typeof TodosRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/favorites/': typeof DashboardFavoritesIndexRoute
  '/dashboard/meetings/': typeof DashboardMeetingsIndexRoute
  '/dashboard/reminders/': typeof DashboardRemindersIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/settings/account/': typeof DashboardSettingsAccountIndexRoute
  '/dashboard/settings/appearance/': typeof DashboardSettingsAppearanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dash'
    | '/todos'
    | '/dashboard/settings'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/contacts/'
    | '/dashboard/favorites/'
    | '/dashboard/meetings/'
    | '/dashboard/reminders/'
    | '/dashboard/settings/'
    | '/dashboard/settings/account/'
    | '/dashboard/settings/appearance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dash'
    | '/todos'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/contacts'
    | '/dashboard/favorites'
    | '/dashboard/meetings'
    | '/dashboard/reminders'
    | '/dashboard/settings'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dash'
    | '/todos'
    | '/dashboard/settings'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/contacts/'
    | '/dashboard/favorites/'
    | '/dashboard/meetings/'
    | '/dashboard/reminders/'
    | '/dashboard/settings/'
    | '/dashboard/settings/account/'
    | '/dashboard/settings/appearance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DashRoute: typeof DashRoute
  TodosRoute: typeof TodosRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/reminders/': {
      id: '/dashboard/reminders/'
      path: '/reminders'
      fullPath: '/dashboard/reminders/'
      preLoaderRoute: typeof DashboardRemindersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/meetings/': {
      id: '/dashboard/meetings/'
      path: '/meetings'
      fullPath: '/dashboard/meetings/'
      preLoaderRoute: typeof DashboardMeetingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/favorites/': {
      id: '/dashboard/favorites/'
      path: '/favorites'
      fullPath: '/dashboard/favorites/'
      preLoaderRoute: typeof DashboardFavoritesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts/'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/appearance/': {
      id: '/dashboard/settings/appearance/'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance/'
      preLoaderRoute: typeof DashboardSettingsAppearanceIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/account/': {
      id: '/dashboard/settings/account/'
      path: '/account'
      fullPath: '/dashboard/settings/account/'
      preLoaderRoute: typeof DashboardSettingsAccountIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
  }
}

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSettingsAccountIndexRoute: typeof DashboardSettingsAccountIndexRoute
  DashboardSettingsAppearanceIndexRoute: typeof DashboardSettingsAppearanceIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
    DashboardSettingsAccountIndexRoute: DashboardSettingsAccountIndexRoute,
    DashboardSettingsAppearanceIndexRoute:
      DashboardSettingsAppearanceIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
  DashboardFavoritesIndexRoute: typeof DashboardFavoritesIndexRoute
  DashboardMeetingsIndexRoute: typeof DashboardMeetingsIndexRoute
  DashboardRemindersIndexRoute: typeof DashboardRemindersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
  DashboardFavoritesIndexRoute: DashboardFavoritesIndexRoute,
  DashboardMeetingsIndexRoute: DashboardMeetingsIndexRoute,
  DashboardRemindersIndexRoute: DashboardRemindersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DashRoute: DashRoute,
  TodosRoute: TodosRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
